### ISSUE TITLE
Feature request and some questions

### ISSUE THREAD

**Issue by dilame** [Effect-TS/schema#12]
I am watching the new `@fp-ts/***` packages with admiration, and just now i have noticed you published `@fp-ts/schema` to NPM and also docs page.
Does it mean it's already ready to use?
And, as long as i have an opportunity to attract your attention in an empty issues list – i would like to ask several questions if i may:

1. Is `@fp-ts/schema` supposed to be a replacement of `io-ts`?
2. Do you have plans to implement `discriminated union` parsing?
3. Do you have plans to implement something like `withMessage()` function in the `@fp-ts/schema`?
4. What's the difference between `JsonCodec` and `Schema`? The APIs looks pretty-similar
5. Will it be possible to implement `@fp-ts/schema`–to–JSONschema converter? As i noticed – there is an AST, but it doesn't look exhaustive. At least for `min/max` filters.

Also i see you implemented an extremely useful filters like `min`, `max`,  `minLength`,  `maxLength`.
I would like to offer some improvements for these filters. 
First of all – it would be more useful to have filters `gt`, `gte`, `lt`, `lte`, `lengthGt`, `lengthGte`, `lengthLt`, `lengthLte`, because it is often needed to check something like `number is between (0, 1)`, not just `[0, 1]`.
And i also noticed these filters don't add any additional brands to the resulting type. Recently i implemented a useful brands for `io-ts` for this purpose – here is the code

```ts
import { brand, BrandC, Branded, number, NumberC } from 'io-ts/es6';

declare const numberGtBrandSymbol: unique symbol;

export type NumberGtBrand<Min extends number> = {
  readonly [key in `NumberGt${Min}`]: typeof numberGtBrandSymbol;
};

export function numberGtBrand<Min extends number>(min: Min): BrandC<NumberC, NumberGtBrand<Min>> {
  return brand(number, (n: number): n is Branded<number, NumberGtBrand<Min>> => n > min, `NumberGt${min}`);
}
```

I hope no need to clarify the idea :) What do you think about adding this concept to the `@fp-ts/schema`? FMPOV it looks according to the FP philosophy

**Comment by dilame** [comment]
Oh, and another question – do you have plans to make ESM a `first-class citizen`?  Because current `io-ts` + `io-ts-types` just doesn't work in ESM mode

**Comment by gcanti** [comment]
> Does it mean it's already ready to use?

It's more a proof of concept at this stage

> Is @fp-ts/schema supposed to be a replacement of io-ts?

Yes

> Do you have plans to implement discriminated union parsing?

Ideally the `union` API should serve both simple unions and discriminated unions (the idea is to analyze the `AST` contained in a `Schema` in order to automatically detect discriminated unions)

> Do you have plans to implement something like withMessage() function

Maybe something like `withCustomError` (I'll add it to my TODO list)

> What's the difference between JsonCodec and Schema? The APIs looks pretty-similar

`JsonCodec` is just one of the targets of `Schema`: you start from a `Schema<A>`, then pass the schema to one of the compilers (like for example `jsonCodecFor`) and you get an artifact like `JsonCodec<A>`

Example

```ts
import * as S from "@fp-ts/schema/Schema"

const PersonSchema = S.struct({
  name: S.string,
  age: S.number,
})

import * as JC from "@fp-ts/schema/JsonCodec"

const PersonJsonCodec = JC.jsonCodecFor(PersonSchema)
```

For convenience the `JsonCodec` exports the same API so you can avoid calling `jsonCodecFor` by hand

```ts
import * as JC from "@fp-ts/schema/JsonCodec"

const PersonJsonCodec = JC.struct({
  name: JC.string,
  age: JC.number,
})
```

but under the hood `JC.struct` just calls `S.struct` and then `jsonCodecFor` for you.

> Will it be possible to implement @fp-ts/schema–to–JSONschema converter?

It should be possible yes (there's a first attempt in the `/test` folder although only hinted) 

> First of all – it would be more useful to have filters gt, gte, lt, lte, lengthGt, lengthGte, lengthLt, lengthLte,

Yeah, I agree, keep in mind that in this early phase they are just examples, I will add several other filters in the near future

> And i also noticed these filters don't add any additional brands to the resulting type

That's intentional, we'll have "filters" which don't change the type (not all users are happy with brands) and we'll have `refinements` which will return a branded type (as soon as we'll have a standard implementation of brands in `@fp-ts/data`)

> do you have plans to make ESM a first-class citizen? 

Yes, all `@fp-ts/*` packages are ESM compatible

**Comment by dilame** [comment]
Thank you for such a detailed reply!

> `JsonCodec` is just one of the targets of `Schema`

Just for example – what could be another target of `Schema`?

> Ideally the union API should serve both simple unions and discriminated unions (the idea is to analyze the AST contained in a Schema in order to automatically detect discriminated unions)

Wow, sounds pretty-grandiose! Do you have plans to implement it?

> That's intentional, we'll have "filters" which don't change the type

Yes, that sounds correct, filters should not change the type. What do you think about implementing a built-in utility refinements on top of built-in filters? I mean like `@fp-ts/schema` have both `gteFilter` and `gteBrand` for folks who cares about strictness? I would like to contribute if there is a ground for it, i just need an example of one of these brands.

And my another 2c – i also often need `unique array` refinement. Do you think this filter/brand worth to be existed in the `@fp-ts/schema?`

**Comment by gcanti** [comment]
> what could be another target of Schema?

Currently

- Decoder
- Encoder
- Guard
- Pretty
- Arbitrary

(I added more infos to the README btw)

> Do you have plans to implement it?

Sure, we are working (right now) on improving the `AST` APIs in order to unlock several features (and detecting discriminated unions is one of them)

> What do you think about implementing a built-in utility

That's the next step sure, but I must wait till we have an official branding system in `@fp-ts/data`

> And my another 2c – i also often need unique array refinement. Do you think this filter/brand worth to be existed in the @fp-ts/schema?

My intention is to provide a way to define your own filters / refinements in userland

**Comment by gcanti** [comment]
> what could be another target of Schema?

Added another compiler in the `/test` folder (`TypeScript`) which converts a schema to a ts type (+ possible related declarations)

```ts
const schema = S.struct({ a: S.number })
const ts = typeScriptFor(schema)
printNodes(ts.nodes) // => { readonly a: number; }
```

**Comment by dilame** [comment]
Thanks for explanation, now `Schema` makes total sense for me!
