### ISSUE TITLE
Parser should support typed Input "I" and Output "O"

### ISSUE THREAD

**Issue by liambutler-lawrence** [Effect-TS/schema#48]
## 🐛 Bug report

I'm porting over our code from io-ts (big improvement!) but am running into issues with `P.encode`.

### Current Behavior

`P.encode(S.literal('foo'))(<some string>)` returns `unknown` instead of `string`. We have a lot of branded (now filtered) and other custom types that we use in our codebase, but we also have lower-level code (e.g. persistence layers, math-heavy algos) that operate over primitives like `io-ts-types`'s `Json` type. We bridge between those two realms with `encode`, which now loses type information and causes lots of compiler errors.

### Expected behavior

In `io-ts`, `t.literal('foo').encode(<some string>)` returned a `string`, not `unknown`.

### Reproducible example

See above.

### Suggested solution(s)

Support primitive input/output types by default (see below as well).

### Additional context

`io-ts` already had this problem with `decode` as well, where the built-in types (e.g. `t.string`) defaulted the `I` type to `unknown`. But the consequence of that was only reduced type safety when bridging from primitives to complex types, whereas the consequence going the other direction (with `encode`) is actual compiler errors, requiring lots of unsafe casts to get our existing code working.

### Your environment

| Software      | Version(s) |
| ------------- | ---------- |
| @fp-ts/schema |    0.0.8        |
| TypeScript    |    4.8.4        |

**Comment by liambutler-lawrence** [comment]
Potential workarounds for the short term are also welcome, I'm aware schema is still in beta :)

**Comment by gcanti** [comment]
In `io-ts`, the main abstraction keeps track of three types, but in `@fp-ts/schema` we've made the decision to only keep track of one type as a design choice (for the time being the main goal is to represent a TypeScript type at runtime).

`Parser` is a artifact produced by a `Schema` and since `Schema` has only one type parameter it is not possible for its derivatives to have more.

I think it is possible to define a different abstraction from `Schema` that still utilizes the `AST` module under the hood and keeps track of additional types depending on the specific use case, but it is something that would need to be studied from the ground up.

**Comment by jessekelly881** [comment]
I think the issue is just an incorrect type casting. This PR(#56) should fix it.

**Comment by stazz** [comment]
Looks like this changed in https://github.com/Effect-TS/schema/commit/df9ea093623640a0e06cdd0147e8e7522ee05110 ?

**Comment by gcanti** [comment]
yeah, people have been wanting a second type parameter for quite some time, there have been several discussions about it in effect Discord
